apiVersion: apps/v1
kind: Deployment

metadata:
  name: taskhub-api

spec:
  replicas: 2

  selector:
    matchLabels:
      app: taskhub-api

  template:
    metadata:
      labels:
        app: taskhub-api

    spec:
      containers:
        - name: backend

          image: findmesubhamsaha/taskhub-backend:latest

          imagePullPolicy: Always

          ports:
            - containerPort: 5000

          envFrom:
            - configMapRef:
                name: taskhub-config

            - secretRef:
                name: taskhub-secret